### ISSUE TITLE
`tickAmount` not documented

### ISSUE THREAD

**Issue by nickdos** [RomRider/apexcharts-card#186]
The README file only has 2 instances of `tickAmount` and both appear in an example config entry:

<img width="848" alt="image" src="https://user-images.githubusercontent.com/532845/126928059-c42c0102-e980-4508-9e79-2de56fd7a17f.png">

Although the variable appears self explanatory, ~I'm not getting predictable output when changing this value from anything but `4`~ (sorted), so wanted to check exactly what this variable does. Seems like it was missed in the "Options" section of the documentation.

**Comment by RomRider** [comment]
It's not specifically documented because it's part of what you can configure with the ApexCharts API of which you can see the documentation [here](https://apexcharts.com/docs/options/yaxis/) (specifically for yaxis, but there's a lot more in that documentation).

That is explained in the documentation in the `apex_config` section.

I'm going to close this.

**Comment by nickdos** [comment]
Thanks for clarifying this. Apologies for missing that detail. Hard to believe that there are another 50+ config options on top of the ~50 you already provide. The mind boggles.
