### ISSUE TITLE
Custom element doesn't exist: apexcharts-card.

### ISSUE THREAD

**Issue by Bach-Danielsson** [RomRider/apexcharts-card#393]
***  issue slowed by a second reboot of the whole system  ***

I have installed the HACS addon and restarted Home Assistant as in the pic bellow .
.
![installed](https://user-images.githubusercontent.com/39077163/189031499-d877667d-20b1-4265-b9b4-56b228a613e8.jpg)
.

Then I try the most simple one but I get  error "Custom element doesn't exist: apexcharts-card." 
And I don't what I need to do to get rid of this error.
.
![error](https://user-images.githubusercontent.com/39077163/189032112-01641ac2-35e0-4e54-9bfe-5f075e4c0698.jpg)
.
I

**Comment by shadowano** [comment]
I have the same problem. 
The documentation says that we have to [add a reference](https://github.com/RomRider/apexcharts-card#add-resource-reference) to it in configuration.yaml 

```
resources:
  - url: /local/apexcharts-card.js?v=2.0.1
    type: module
```

This gives an validation error. 
![image](https://user-images.githubusercontent.com/3582807/199213306-b9aefe38-c81d-4698-852b-43b0ae57250a.png)

I have the following files on this path:
![image](https://user-images.githubusercontent.com/3582807/199213435-acc76cc1-b80b-477e-b229-3fc3e10ea9a1.png)

Home Assistant 2022.10.5
Supervisor 2022.10.0
Operating System 9.3
Frontend 20221010.0 - latest

**Comment by shadowano** [comment]
@Bach-Danielsson If you found a way to solve the issue you had, could you please describe what you did to solve it?

**Comment by shadowano** [comment]
hmm... I googled a bit, and found this https://community.home-assistant.io/t/component-error-resources-integration-resources-not-found/143120/5. The resource was already listed there for me. Suddenly I found the card when trying to add a new card. Not sure what magic fixed this...

**Comment by mnordstr** [comment]
I had the same issue, after installing via HACS, did not show up even after restart of HA. What solved it was a complete reboot of the host (Raspberry Pi 4), from Settings->System->Hardware->(three dots)->Reboot system. A normal restart for some reason was not enough.

**Comment by nirvanaa-s-cat** [comment]
Hi, I had the same problem. I have installed HACS and some of the required repositories (6). I cannot add a card because it is not known by the system. I found that the resources are not listed. 2 days of waiting and no information on what to do. On the 3rd day I added a new card and it worked fine. So I removed all the repositories from the first day and reinstalled them. Tada, it works! 

In my opinion, after installing HACS the system needs time for something and one or two days later everything is properly initialised. then you can add the repos and it will work.

**Comment by dotnetrix** [comment]
I have it available if I visit HA by local 196.168.xxx.xxx:8123, but not if I visit by homassistant.local:8123. I haven't set up to visit externally yet, so don't know if that would also have the same issue.
I did install via 196.168.xxx.xxx, so I guess that's why it's available there.

**Comment by WimDeceuninck** [comment]
Today, I have experienced the 'Custom element doesn't exist: apexcharts-card' issue.  Resolution to restore the 'apexchart-cards' on my system was to 'manage resources' and just 'update' without changing anything (step 1 of the suggestions below) .

Found this via Google search 'custom element doesn't exist apexcharts-card', :-) :

> If you're encountering the "Custom element doesn't exist: apexcharts-card" issue in Home Assistant, here are a few steps you can try to resolve it:
> 
> **1. **Update Resources**:
>    - Click the three dots in the top right corner (overflow button) within Home Assistant.
>    - Search for the specific resource (in this case, "apexcharts-card").
>    - Open the resource.
>    - Click **UPDATE** without changing any resource information.
>    - The card should now appear.**
> 
> 2. **Clear Browser Cache**:
>    - Sometimes browser caching can cause issues with loading resources.
>    - Try refreshing or hard-refreshing your browser cache after adding the card.



Remember that Home Assistant's ecosystem is constantly evolving, and sometimes issues arise due to updates or changes. If the problem persists, consider checking the project's GitHub repository or community forums for additional troubleshooting steps or updates².

Source: Conversation with Bing, 28/2/2024
([1](https://community.home-assistant.io/t/solved-yet-another-custom-element-doesnt-exist-issue/632538)) [SOLVED] Yet Another....Custom Element Doesn't Exist Issue. https://community.home-assistant.io/t/solved-yet-another-custom-element-doesnt-exist-issue/632538.
(2) Custom element doesn't exist: apexcharts-card. #393 - GitHub. https://github.com/RomRider/apexcharts-card/issues/393.
(3) Constant "Custom element doesn't exist" errors #511 - GitHub. https://github.com/UI-Lovelace-Minimalist/UI/issues/511.
(4) Custom element doesn't exist: config-template-card #96 - GitHub. https://github.com/iantrich/config-template-card/issues/96.

**Comment by carryonrewardless** [comment]
Also try a browser reset/clear cache.

**Comment by soinipe** [comment]
I had the same problem. I'm running HA with Docker Compose. HA restart or docker compose down&up did not help. Coincidence or not: added one chart with other browser (Edge) and was then able to add chart also with the original browser (Chrome).

**Comment by tkahn** [comment]
I solved it by activating developer tools in Chrome, disable cache under network and a hard refresh.
