### ISSUE TITLE
Add support of grouped stacked bar charts

### ISSUE THREAD

**Issue by raldone01** [RomRider/apexcharts-card#673]
![image](https://github.com/RomRider/apexcharts-card/assets/27293675/75ff2a10-d3be-4134-8c7e-c331ae933698)

I plot the power consumption of my tracked devices daily, monthly, ...
I would love to add another bar next to the stacked bar with my total consumption so I can get an idea of how much energy usage I am not tracking.

Apex Charts should already support this with stacked groups.
A older issue also mentioned this #550.

**Describe the solution you'd like**
Support for grouped stacked columns would be splendid.

**Describe alternatives you've considered**
I tried two charts next to each other but its just not the same.
The y axis scale is not the same.

**Comment by raldone01** [comment]
Not stale...

**Comment by georgepauna** [comment]
See this rejected pull request (I have the exact same scenario):
https://github.com/RomRider/apexcharts-card/pull/711

Meanwhile you can use a different Y axis ID for the total and you'll get what you want:
IMPORTANT: You must have a different chart style for total so that this works (e.g. use bars for current series and line or area for total)

![image](https://github.com/RomRider/apexcharts-card/assets/42321881/21e9e3eb-fcc8-44c3-9fc9-0e7c06381d0d)

**Comment by RomRider** [comment]
Grouped stacked colums are not supported on time series in apexcharts.js.
