### ISSUE TITLE
Add total datalabel on stacked charts

### ISSUE THREAD

**Issue by Toukite** [RomRider/apexcharts-card#73]
Hello,

With a bar graph like this one:
![image](https://user-images.githubusercontent.com/42780622/107427651-f2691d80-6b21-11eb-8021-a9490714fd91.png)

I would like to know if it would be possible to display the total datalabel per column instead of the label for each element in the stack. 
So for column 1 display only 18.4, column 2 display only 23.7, ...
I think that's what they discuss here https://github.com/apexcharts/apexcharts.js/issues/450 but I'm not sure if have access to formatter here ?

**Comment by RomRider** [comment]
You can't define a formatter but I can probably offer this option. I'll investigate!

Thanks for the link to the feature request, it helps.

**Comment by Toukite** [comment]
Hi, 
Thank you for taking this into account !
I tried what you put on dev and I would have 2 remarks:
![image](https://user-images.githubusercontent.com/42780622/107672700-80b1e080-6c95-11eb-8802-13d3a6d9c436.png)

1. Maybe this total option should be more on the header level (next to stacked option) and be equals to true/false, than on the series level.
This way, we could choose what we want: either indivual values, or total, or both
With current implementation, we can display the total twice (or rather, have it as many times as the number of series), but we can't display everything because we would miss the partial value of the series where we put the total value.
I'm personnally only interested in the total, but the current implementation highlights the fact that someone could use displaying all of them + total. What do you think ?

2. Apparently, there is something to do about rounding :D not sure if it should be handled by the card or earlier (provide well formatted data to the card). What do you think ?

**Comment by RomRider** [comment]
> 1. This way, we could choose what we want: either indivual values, or total, or both

There's no possibility to display the value and the total at the same time unfortunately because a datalabel is linked to a serie (this is how it is done in ApexCharts) and the values you have as total in your green boxes are actually using the datalabel of the green serie. And this is why I let the user chose between displaying the total or the individual value this way. There's not more possibilities unfortunately :(



> 2\. Apparently, there is something to do about rounding :D for the middle column, individual values are 11,6 and 13,7, not sure how the sum comes up with this 25,299999999999 thing

That's javascript averaging numbers (the individual value are actually not with 1 digit after the `.` but with more, I just **display** them by default with only 1 to avoid that behaviour you are seeing, but they are not truncated in the actual data used to display the chart). I forgot to apply that same logic to the total, I'll fix that :)

**Comment by Toukite** [comment]
Regarding first point, maybe another idea then: in addition to true/false/total, could we display any variable we want ?
This way, I could imagine having the total on upper bar, and maybe percentage on lower bar instead of its value ? 
Not really a need, just wanted to share the thought

**Comment by RomRider** [comment]
> I could imagine having the total on upper bar, and maybe percentage on lower bar instead of its value ?

I guess %age would be possible since we know the total and the value of the current serie. I'll look into that

**Comment by Toukite** [comment]
Ok thanks ! Just to clarify, % was just an example, I was wondering if we could put an entity in there
